- name: Add ec2 instances to ELB
  hosts: localhost
  connection: local

  tasks:
    - name: Add 1st EC2 instance to the ELB
      ec2_elb:
        state: present
        ec2_elbs: "{{ awsinfra_lb_name }}"
        region: "{{ item.region }}"
        instance_id: "{{ item.id }}"
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
      with_items: "{{ ec2web.results[0].tagged_instances }}"

    - name: Add 2nd EC2 instance to the ELB
      ec2_elb:
        state: present
        ec2_elbs: "{{ awsinfra_lb_name }}"
        region: "{{ item.region }}"
        instance_id: "{{ item.id }}"
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
      with_items: "{{ ec2web.results[1].tagged_instances }}"    
