- name: Set-up httpd on webservers
  hosts: webservers
  remote_user: ec2-user
  become: true
  become_method: sudo
  connection: ssh

  tasks:
   - name: ensure apache is at the latest version
     yum: name=httpd state=latest

   - name: Create default index page
     copy:
       dest: /var/www/html/index.html
       content: "Hello from {{ ansible_hostname }}"

   - name: Restart httpd
     service:
       name: httpd
       state: restarted
